"""Generate the OpenSCAD dimensions include from project_spec.py."""

from pathlib import Path
import sys

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.project_spec import (
    BATTERY_BAY,
    BOX,
    BUTTON_HOLE_DIAMETER,
    DIAL_OPENING_DIAMETER,
    LED_HOLE_DIAMETER,
    MASTER_SWITCH_SIZE,
    PANEL_FEATURES,
    ROCKER_SIZE,
)


def scad_value(value):
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, (tuple, list)):
        return "[" + ", ".join(scad_value(item) for item in value) + "]"
    return str(value).lower()


def generate_dimensions_text():
    positions = {feature["id"]: [feature["x"], feature["y"]] for feature in PANEL_FEATURES}
    values = {
        "box_w": BOX["width"],
        "box_h": BOX["height"],
        "box_d": BOX["depth"],
        "corner_r": BOX["corner_radius"],
        "wall": BOX["wall"],
        "front_t": BOX["front"],
        "back_t": BOX["back"],
        "fit_clearance": BOX["clearance"],
        "led_hole_d": LED_HOLE_DIAMETER,
        "button_hole_d": BUTTON_HOLE_DIAMETER,
        "rocker_size": ROCKER_SIZE,
        "dial_opening_d": DIAL_OPENING_DIAMETER,
        "master_switch_size": MASTER_SWITCH_SIZE,
        "battery_bay_size": [BATTERY_BAY["width"], BATTERY_BAY["height"], BATTERY_BAY["depth"]],
        "battery_bay_pos": [BATTERY_BAY["x"], BATTERY_BAY["y"]],
    }
    values.update({f"pos_{key}": value for key, value in positions.items()})
    lines = ["// Generated by tools/generate_dimensions.py; do not edit by hand."]
    lines.extend(f"{name} = {scad_value(value)};" for name, value in values.items())
    return "\n".join(lines) + "\n"


def main():
    output = Path("cad/generated_dimensions.scad")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generate_dimensions_text(), encoding="utf-8")
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
